# Generated by Django 3.2 on 2023-09-04 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.TextField(blank=True, db_column='user_nickname', null=True, verbose_name='user_nickname'),
        ),
    ]
